### ISSUE TITLE
F722 is missing: do not use bare 'except'

### ISSUE THREAD

**Issue by jugmac00** [grantmcconnaughey/Flake8Rules#27] opened 2020-02-20 12:44 UTC

**Comment by jugmac00** [comment] 2020-02-21 14:44
I just saw this is a duplicate of #15 - which is already 10 months old.

I understand, you got more important stuff to do currently, but would you accept a PR?

**Comment by grantmcconnaughey** [comment] 2020-03-01 16:53
@jugmac00 yes, absolutely! PRs are very much appreciated.

**Comment by grantmcconnaughey** [comment] 2020-05-16 15:42
Duplicate of #15

**Closed as completed by grantmcconnaughey** 2020-05-16 15:42 UTC

**Comment by grantmcconnaughey** [comment] 2020-05-16 15:48
Fixed!

**Comment by jugmac00** [comment] 2020-05-16 17:37
Sorry for not contributing as I planned - it is like a curse. So many great open source projects out there, and only so and so much time!

Thank you very much! Your site was such a huge help when I started using flake8 on my inherited, huge Python project.
